language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4.12
  - DJANGO=1.5.7
  - DJANGO=1.6.4
install:
  - pip install -q Django==$DJANGO
  - pip install -q flake8
  - pip install -q -e .
script:
  - make test
