language: python
services:
  - memcached
  - redis-server
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4.12
  - DJANGO=1.5.7
  - DJANGO=1.6.4
install:
  - pip install Django==$DJANGO
  - pip install flake8
  - pip install -e .
script:
  - make test
